name: CI - Test bn Utility

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Test when no arguments are given
      run: ./bn.sh > test_results.txt
      continue-on-error: true

    - name: Test year outside of allowed range
      run: ./bn.sh 2030 F > test_results.txt
      continue-on-error: true

    - name: Test invalid gender
      run: ./bn.sh 2019 A > test_results.txt
      continue-on-error: true

    - name: Test invalid name format
      run: ./bn.sh 2000 F <<< "lucy2"
      continue-on-error: true

    - name: Test for non-existent file
      run: ./bn.sh 1801 f <<< "lucy"
      continue-on-error: true

    - name: Test --help flag
      run: ./bn.sh --help

    - name: Test for Lucy in 1880 (44/942)
      run: ./bn.sh 1880 F <<< "lucy"

    - name: Test for Payton in 1880 (1028/1058)
      run: ./bn.sh 1880 m <<< "Payton"

    - name: Test for name not ranked in 2022
      run: ./bn.sh 2022 M <<< "Skibidi"
      continue-on-error: true

    - name: Test for Sam in 2022
      run: ./bn.sh 2022 b <<< "sam"

    - name: Run the test_script
      run: ./test_script > test_results.txt

    - name: Upload Test Results
      if: ${{ always() }}

      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: ./test_results.txt