name: CI - Test bn Utility

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Test when no arguments are given
      run: ./bn.sh > test_results.txt

    - name: Test year outside of allowed range
      run: ./bn.sh 2030 F > test_results.txt

    - name: Test invalid gender
      run: ./bn.sh 2019 A > test_results.txt

    - name: Test --help flag
      run: ./bn.sh --help

    - name: Upload Test Results
      if: ${{ always() }}

      uses: actions/upload-artifact@v4
      with:
        name: Test Results
        path: ./test_results.txt